In [1]:
# Importing required libraries

import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [2]:
# Reading Predictions from pred.csv
df = pd.read_csv('../predictions/pred.csv')

In [3]:
df.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
0,0,203.163818,105.991051,180.778702,186.944504,149.566711,192.127151,214.613220,294.843750,275.926086,299.511810,217.613113,185.639923,251.928894,270.017151,235.720383,286.329895,196.626099,364.129883,214.453308,507.276672,206.773026,624.251526,260.080017,350.290253,337.061737,473.284973,322.720612,604.698853,196.990280,94.761299,208.627869,87.957047,171.772949,109.954994,168.205658,107.305519
1,1,261.551483,111.630043,255.992157,193.397278,210.391556,199.696945,212.899612,276.385895,237.557465,287.787231,304.495789,194.783356,339.439972,271.893982,335.832642,300.212646,241.059158,370.228058,236.882111,512.012451,255.464035,623.429321,311.641296,363.868042,349.667175,498.357605,338.588135,620.232483,252.779144,96.701103,269.565308,95.074379,231.819122,119.923584,263.201538,115.319519
2,2,288.109589,108.774521,291.212341,198.792450,243.121292,204.756546,211.037445,258.190552,227.945862,266.982300,347.035583,195.326920,393.706848,257.559875,393.331604,295.267609,259.911407,371.733521,245.754837,507.218079,266.177124,620.237549,336.451477,368.632629,352.670135,497.125763,345.849457,615.352478,262.242279,83.541534,293.690491,91.343941,249.833237,117.023842,295.028198,116.414024
3,3,292.621429,118.389900,299.582489,201.997803,252.681564,207.814041,216.720230,266.580902,233.538620,284.192505,351.819214,198.567459,392.213531,261.304443,387.966522,301.810211,267.562195,373.959259,254.392776,505.105103,264.550568,621.086121,339.406006,370.668335,352.799591,499.425995,349.966644,615.784058,279.143372,101.571808,302.756378,104.666763,244.379776,120.823318,299.283447,117.039413
4,4,288.923065,96.833412,288.799469,185.567413,230.754623,188.577927,212.207855,265.992371,220.161346,289.329620,344.360870,188.951767,382.663147,263.897705,394.429749,304.104584,257.515381,364.368164,220.973618,498.229828,246.376801,615.247192,333.747894,363.965576,342.588165,503.416992,348.678345,619.070251,264.587128,82.868874,293.277191,75.222801,223.462006,100.096718,296.168762,112.708191

In [4]:
# Removing Unwanted column
df = df.iloc[:,1:]

In [5]:
df.shape

(300, 36)

In [6]:
# # Reading background image for video
frame = cv2.imread('black.jpg')

In [7]:
# Creating Pairs to connect coordinates
POSE_PAIRS = [[0,1], [1,2], [2,3], [3,4], [1,5], [5,6], [6,7], [2,8], [8,9], [9,10], [5,11], [11,12], [12,13], [8,11]]

In [8]:
# Creating VideoWriter object
vid_writer = cv2.VideoWriter('output.avi',cv2.VideoWriter_fourcc('M','J','P','G'), 10, (frame.shape[1],frame.shape[0]))

In [10]:
# Draw Skeleton

for ij in range(0,300):
    # Reading background image for video
    frame = cv2.imread('black.jpg')
    
    # Creating a tuple and a list to read coordinates from dataframe
    coor = ()
    points = []
    
    # Storing coordinates in the list points
    for i in range(0,36,2):
        coor = (int(df.iloc[ij,i]),) + (int(df.iloc[ij,i+1]),)
        points.append(coor)

    # Generating AI boody
    for pair in POSE_PAIRS:
        partA = pair[0]
        partB = pair[1]

        if points[partA] and points[partB]:
            cv2.line(frame, points[partA], points[partB], (191, 201, 202), 3, lineType = 8)
            cv2.circle(frame, points[partA], 7, (0, 0, 150), thickness=-1, lineType=cv2.FILLED)
            cv2.circle(frame, points[partB], 7, (0, 0, 150), thickness=-1, lineType=cv2.FILLED)
    
    # Showing generated frames
    cv2.imshow('Output-Skeleton', frame)
    
    # Writing frames to vid_writer object
    vid_writer.write(frame)

# Releasing Final video
vid_writer.release()